import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const opensans = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Gracjan Drozdek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en" className="scroll-smooth">
      <body className={`${opensans.className}`}>
        <header className="site-header">
          <Header/>
        </header>
        <main id="main-content">
          {children}
        </main>
        <footer className="site-footer">

        </footer>
      </body>
    </html>
    </>
  );
}
